-- AlterTable
ALTER TABLE `estudos` ADD COLUMN `metaParticipantes` INTEGER NULL,
    ADD COLUMN `status` ENUM('PLANEJAMENTO', 'EM_ANDAMENTO', 'COLETA_ENCERRADA', 'ARQUIVADO') NOT NULL DEFAULT 'PLANEJAMENTO';
